# Generated by Django 5.2.6 on 2025-09-22 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(choices=[('AVAX', 'AVAX'), ('USDT', 'USDT')], max_length=10)),
                ('amount_decimal', models.DecimalField(decimal_places=6, max_digits=20)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('chain_id', models.IntegerField(default=43113)),
                ('donor_telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='donations.botuser')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='campaigns.campaign')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_donations', to='ngos.ngo')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ngo', 'created_at'], name='donations_d_ngo_id_4f31a0_idx'), models.Index(fields=['campaign', 'created_at'], name='donations_d_campaig_2774f3_idx'), models.Index(fields=['donor_telegram_id', 'created_at'], name='donations_d_donor_t_701066_idx'), models.Index(fields=['tx_hash'], name='donations_d_tx_hash_4fcada_idx')],
            },
        ),
    ]
