# Generated by Django 5.2.6 on 2025-09-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_enhancements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='donation',
            new_name='donations_d_recipie_6f0113_idx',
            old_name='donations_d_recipient_3d0e8d_idx',
        ),
        migrations.RenameIndex(
            model_name='donationintent',
            new_name='donations_d_wallet__1ccb2b_idx',
            old_name='donationin_wallet__69ab82_idx',
        ),
        migrations.RenameIndex(
            model_name='donationintent',
            new_name='donations_d_donor_t_08788b_idx',
            old_name='donationin_donor_t_6bc256_idx',
        ),
    ]
