# Generated by Django 5.2.6 on 2025-09-24 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('telegram_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bot_users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('telegram_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_state', to='bot_state.botuser')),
            ],
            options={
                'db_table': 'bot_conversation_state',
            },
        ),
        migrations.CreateModel(
            name='IntentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=64)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0)),
                ('handled', models.BooleanField(default=False)),
                ('error_messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intent_logs', to='bot_state.botuser')),
            ],
            options={
                'db_table': 'bot_intent_logs',
                'indexes': [models.Index(fields=['created_at'], name='bot_intent__created_a2661b_idx'), models.Index(fields=['intent'], name='bot_intent__intent_7a1192_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='bot_state.botuser')),
            ],
            options={
                'db_table': 'bot_message_deliveries',
                'indexes': [models.Index(fields=['status', 'created_at'], name='bot_message_status_f59117_idx')],
            },
        ),
    ]
