[mypy]
files = telbot_llm
ignore_missing_imports = True
strict = True
disallow_untyped_calls = True
disallow_untyped_defs = True
warn_return_any = True
warn_unused_ignores = True
check_untyped_defs = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
disallow_any_generics = True
disallow_any_unimported = True
disallow_any_expr = True
disallow_any_decorated = True
disallow_any_explicit = True
disallow_untyped_decorators = True
disallow_untyped_lambda = True
show_error_context = True
show_column_numbers = True
pretty = True